// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Proto/Common/Object.proto

package fr.kissy.hellion.proto.common;

public final class ObjectDto {
  private ObjectDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ObjectProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated .ObjectProto.SystemObjectProto systemObjects = 2;
    /**
     * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
     */
    java.util.List<fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto> 
        getSystemObjectsList();
    /**
     * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
     */
    fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto getSystemObjects(int index);
    /**
     * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
     */
    int getSystemObjectsCount();
    /**
     * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
     */
    java.util.List<? extends fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProtoOrBuilder> 
        getSystemObjectsOrBuilderList();
    /**
     * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
     */
    fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProtoOrBuilder getSystemObjectsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ObjectProto}
   */
  public static final class ObjectProto extends
      com.google.protobuf.GeneratedMessage
      implements ObjectProtoOrBuilder {
    // Use ObjectProto.newBuilder() to construct.
    private ObjectProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ObjectProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ObjectProto defaultInstance;
    public static ObjectProto getDefaultInstance() {
      return defaultInstance;
    }

    public ObjectProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ObjectProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                systemObjects_ = new java.util.ArrayList<fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto>();
                mutable_bitField0_ |= 0x00000002;
              }
              systemObjects_.add(input.readMessage(fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          systemObjects_ = java.util.Collections.unmodifiableList(systemObjects_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fr.kissy.hellion.proto.common.ObjectDto.internal_static_ObjectProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fr.kissy.hellion.proto.common.ObjectDto.internal_static_ObjectProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.class, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.Builder.class);
    }

    public static com.google.protobuf.Parser<ObjectProto> PARSER =
        new com.google.protobuf.AbstractParser<ObjectProto>() {
      public ObjectProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObjectProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ObjectProto> getParserForType() {
      return PARSER;
    }

    public interface SystemObjectProtoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required .SystemProto.Type systemType = 10;
      /**
       * <code>required .SystemProto.Type systemType = 10;</code>
       */
      boolean hasSystemType();
      /**
       * <code>required .SystemProto.Type systemType = 10;</code>
       */
      fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type getSystemType();

      // repeated .PropertyProto properties = 11;
      /**
       * <code>repeated .PropertyProto properties = 11;</code>
       */
      java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> 
          getPropertiesList();
      /**
       * <code>repeated .PropertyProto properties = 11;</code>
       */
      fr.kissy.hellion.proto.common.PropertyDto.PropertyProto getProperties(int index);
      /**
       * <code>repeated .PropertyProto properties = 11;</code>
       */
      int getPropertiesCount();
      /**
       * <code>repeated .PropertyProto properties = 11;</code>
       */
      java.util.List<? extends fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder> 
          getPropertiesOrBuilderList();
      /**
       * <code>repeated .PropertyProto properties = 11;</code>
       */
      fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder getPropertiesOrBuilder(
          int index);

      // optional string type = 12;
      /**
       * <code>optional string type = 12;</code>
       */
      boolean hasType();
      /**
       * <code>optional string type = 12;</code>
       */
      java.lang.String getType();
      /**
       * <code>optional string type = 12;</code>
       */
      com.google.protobuf.ByteString
          getTypeBytes();
    }
    /**
     * Protobuf type {@code ObjectProto.SystemObjectProto}
     */
    public static final class SystemObjectProto extends
        com.google.protobuf.GeneratedMessage
        implements SystemObjectProtoOrBuilder {
      // Use SystemObjectProto.newBuilder() to construct.
      private SystemObjectProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private SystemObjectProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final SystemObjectProto defaultInstance;
      public static SystemObjectProto getDefaultInstance() {
        return defaultInstance;
      }

      public SystemObjectProto getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private SystemObjectProto(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 80: {
                int rawValue = input.readEnum();
                fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type value = fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(10, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  systemType_ = value;
                }
                break;
              }
              case 90: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  properties_ = new java.util.ArrayList<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto>();
                  mutable_bitField0_ |= 0x00000002;
                }
                properties_.add(input.readMessage(fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.PARSER, extensionRegistry));
                break;
              }
              case 98: {
                bitField0_ |= 0x00000002;
                type_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            properties_ = java.util.Collections.unmodifiableList(properties_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.kissy.hellion.proto.common.ObjectDto.internal_static_ObjectProto_SystemObjectProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.kissy.hellion.proto.common.ObjectDto.internal_static_ObjectProto_SystemObjectProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.class, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder.class);
      }

      public static com.google.protobuf.Parser<SystemObjectProto> PARSER =
          new com.google.protobuf.AbstractParser<SystemObjectProto>() {
        public SystemObjectProto parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SystemObjectProto(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<SystemObjectProto> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required .SystemProto.Type systemType = 10;
      public static final int SYSTEMTYPE_FIELD_NUMBER = 10;
      private fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type systemType_;
      /**
       * <code>required .SystemProto.Type systemType = 10;</code>
       */
      public boolean hasSystemType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .SystemProto.Type systemType = 10;</code>
       */
      public fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type getSystemType() {
        return systemType_;
      }

      // repeated .PropertyProto properties = 11;
      public static final int PROPERTIES_FIELD_NUMBER = 11;
      private java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> properties_;
      /**
       * <code>repeated .PropertyProto properties = 11;</code>
       */
      public java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> getPropertiesList() {
        return properties_;
      }
      /**
       * <code>repeated .PropertyProto properties = 11;</code>
       */
      public java.util.List<? extends fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder> 
          getPropertiesOrBuilderList() {
        return properties_;
      }
      /**
       * <code>repeated .PropertyProto properties = 11;</code>
       */
      public int getPropertiesCount() {
        return properties_.size();
      }
      /**
       * <code>repeated .PropertyProto properties = 11;</code>
       */
      public fr.kissy.hellion.proto.common.PropertyDto.PropertyProto getProperties(int index) {
        return properties_.get(index);
      }
      /**
       * <code>repeated .PropertyProto properties = 11;</code>
       */
      public fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder getPropertiesOrBuilder(
          int index) {
        return properties_.get(index);
      }

      // optional string type = 12;
      public static final int TYPE_FIELD_NUMBER = 12;
      private java.lang.Object type_;
      /**
       * <code>optional string type = 12;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string type = 12;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string type = 12;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        systemType_ = fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type.None;
        properties_ = java.util.Collections.emptyList();
        type_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasSystemType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        for (int i = 0; i < getPropertiesCount(); i++) {
          if (!getProperties(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(10, systemType_.getNumber());
        }
        for (int i = 0; i < properties_.size(); i++) {
          output.writeMessage(11, properties_.get(i));
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(12, getTypeBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(10, systemType_.getNumber());
        }
        for (int i = 0; i < properties_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(11, properties_.get(i));
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(12, getTypeBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ObjectProto.SystemObjectProto}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProtoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return fr.kissy.hellion.proto.common.ObjectDto.internal_static_ObjectProto_SystemObjectProto_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return fr.kissy.hellion.proto.common.ObjectDto.internal_static_ObjectProto_SystemObjectProto_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.class, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder.class);
        }

        // Construct using fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getPropertiesFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          systemType_ = fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type.None;
          bitField0_ = (bitField0_ & ~0x00000001);
          if (propertiesBuilder_ == null) {
            properties_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            propertiesBuilder_.clear();
          }
          type_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return fr.kissy.hellion.proto.common.ObjectDto.internal_static_ObjectProto_SystemObjectProto_descriptor;
        }

        public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto getDefaultInstanceForType() {
          return fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.getDefaultInstance();
        }

        public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto build() {
          fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto buildPartial() {
          fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto result = new fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.systemType_ = systemType_;
          if (propertiesBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              properties_ = java.util.Collections.unmodifiableList(properties_);
              bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.properties_ = properties_;
          } else {
            result.properties_ = propertiesBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto) {
            return mergeFrom((fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto other) {
          if (other == fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.getDefaultInstance()) return this;
          if (other.hasSystemType()) {
            setSystemType(other.getSystemType());
          }
          if (propertiesBuilder_ == null) {
            if (!other.properties_.isEmpty()) {
              if (properties_.isEmpty()) {
                properties_ = other.properties_;
                bitField0_ = (bitField0_ & ~0x00000002);
              } else {
                ensurePropertiesIsMutable();
                properties_.addAll(other.properties_);
              }
              onChanged();
            }
          } else {
            if (!other.properties_.isEmpty()) {
              if (propertiesBuilder_.isEmpty()) {
                propertiesBuilder_.dispose();
                propertiesBuilder_ = null;
                properties_ = other.properties_;
                bitField0_ = (bitField0_ & ~0x00000002);
                propertiesBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getPropertiesFieldBuilder() : null;
              } else {
                propertiesBuilder_.addAllMessages(other.properties_);
              }
            }
          }
          if (other.hasType()) {
            bitField0_ |= 0x00000004;
            type_ = other.type_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasSystemType()) {
            
            return false;
          }
          for (int i = 0; i < getPropertiesCount(); i++) {
            if (!getProperties(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required .SystemProto.Type systemType = 10;
        private fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type systemType_ = fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type.None;
        /**
         * <code>required .SystemProto.Type systemType = 10;</code>
         */
        public boolean hasSystemType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .SystemProto.Type systemType = 10;</code>
         */
        public fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type getSystemType() {
          return systemType_;
        }
        /**
         * <code>required .SystemProto.Type systemType = 10;</code>
         */
        public Builder setSystemType(fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          systemType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .SystemProto.Type systemType = 10;</code>
         */
        public Builder clearSystemType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          systemType_ = fr.kissy.hellion.proto.common.SystemDto.SystemProto.Type.None;
          onChanged();
          return this;
        }

        // repeated .PropertyProto properties = 11;
        private java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> properties_ =
          java.util.Collections.emptyList();
        private void ensurePropertiesIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            properties_ = new java.util.ArrayList<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto>(properties_);
            bitField0_ |= 0x00000002;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
            fr.kissy.hellion.proto.common.PropertyDto.PropertyProto, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder, fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder> propertiesBuilder_;

        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> getPropertiesList() {
          if (propertiesBuilder_ == null) {
            return java.util.Collections.unmodifiableList(properties_);
          } else {
            return propertiesBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public int getPropertiesCount() {
          if (propertiesBuilder_ == null) {
            return properties_.size();
          } else {
            return propertiesBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public fr.kissy.hellion.proto.common.PropertyDto.PropertyProto getProperties(int index) {
          if (propertiesBuilder_ == null) {
            return properties_.get(index);
          } else {
            return propertiesBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public Builder setProperties(
            int index, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto value) {
          if (propertiesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensurePropertiesIsMutable();
            properties_.set(index, value);
            onChanged();
          } else {
            propertiesBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public Builder setProperties(
            int index, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder builderForValue) {
          if (propertiesBuilder_ == null) {
            ensurePropertiesIsMutable();
            properties_.set(index, builderForValue.build());
            onChanged();
          } else {
            propertiesBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public Builder addProperties(fr.kissy.hellion.proto.common.PropertyDto.PropertyProto value) {
          if (propertiesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensurePropertiesIsMutable();
            properties_.add(value);
            onChanged();
          } else {
            propertiesBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public Builder addProperties(
            int index, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto value) {
          if (propertiesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensurePropertiesIsMutable();
            properties_.add(index, value);
            onChanged();
          } else {
            propertiesBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public Builder addProperties(
            fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder builderForValue) {
          if (propertiesBuilder_ == null) {
            ensurePropertiesIsMutable();
            properties_.add(builderForValue.build());
            onChanged();
          } else {
            propertiesBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public Builder addProperties(
            int index, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder builderForValue) {
          if (propertiesBuilder_ == null) {
            ensurePropertiesIsMutable();
            properties_.add(index, builderForValue.build());
            onChanged();
          } else {
            propertiesBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public Builder addAllProperties(
            java.lang.Iterable<? extends fr.kissy.hellion.proto.common.PropertyDto.PropertyProto> values) {
          if (propertiesBuilder_ == null) {
            ensurePropertiesIsMutable();
            super.addAll(values, properties_);
            onChanged();
          } else {
            propertiesBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public Builder clearProperties() {
          if (propertiesBuilder_ == null) {
            properties_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
          } else {
            propertiesBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public Builder removeProperties(int index) {
          if (propertiesBuilder_ == null) {
            ensurePropertiesIsMutable();
            properties_.remove(index);
            onChanged();
          } else {
            propertiesBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder getPropertiesBuilder(
            int index) {
          return getPropertiesFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder getPropertiesOrBuilder(
            int index) {
          if (propertiesBuilder_ == null) {
            return properties_.get(index);  } else {
            return propertiesBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public java.util.List<? extends fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder> 
             getPropertiesOrBuilderList() {
          if (propertiesBuilder_ != null) {
            return propertiesBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(properties_);
          }
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder addPropertiesBuilder() {
          return getPropertiesFieldBuilder().addBuilder(
              fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.getDefaultInstance());
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder addPropertiesBuilder(
            int index) {
          return getPropertiesFieldBuilder().addBuilder(
              index, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.getDefaultInstance());
        }
        /**
         * <code>repeated .PropertyProto properties = 11;</code>
         */
        public java.util.List<fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder> 
             getPropertiesBuilderList() {
          return getPropertiesFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            fr.kissy.hellion.proto.common.PropertyDto.PropertyProto, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder, fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder> 
            getPropertiesFieldBuilder() {
          if (propertiesBuilder_ == null) {
            propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                fr.kissy.hellion.proto.common.PropertyDto.PropertyProto, fr.kissy.hellion.proto.common.PropertyDto.PropertyProto.Builder, fr.kissy.hellion.proto.common.PropertyDto.PropertyProtoOrBuilder>(
                    properties_,
                    ((bitField0_ & 0x00000002) == 0x00000002),
                    getParentForChildren(),
                    isClean());
            properties_ = null;
          }
          return propertiesBuilder_;
        }

        // optional string type = 12;
        private java.lang.Object type_ = "";
        /**
         * <code>optional string type = 12;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string type = 12;</code>
         */
        public java.lang.String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            type_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string type = 12;</code>
         */
        public com.google.protobuf.ByteString
            getTypeBytes() {
          java.lang.Object ref = type_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            type_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string type = 12;</code>
         */
        public Builder setType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string type = 12;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000004);
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        /**
         * <code>optional string type = 12;</code>
         */
        public Builder setTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          type_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ObjectProto.SystemObjectProto)
      }

      static {
        defaultInstance = new SystemObjectProto(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ObjectProto.SystemObjectProto)
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .ObjectProto.SystemObjectProto systemObjects = 2;
    public static final int SYSTEMOBJECTS_FIELD_NUMBER = 2;
    private java.util.List<fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto> systemObjects_;
    /**
     * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
     */
    public java.util.List<fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto> getSystemObjectsList() {
      return systemObjects_;
    }
    /**
     * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
     */
    public java.util.List<? extends fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProtoOrBuilder> 
        getSystemObjectsOrBuilderList() {
      return systemObjects_;
    }
    /**
     * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
     */
    public int getSystemObjectsCount() {
      return systemObjects_.size();
    }
    /**
     * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
     */
    public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto getSystemObjects(int index) {
      return systemObjects_.get(index);
    }
    /**
     * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
     */
    public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProtoOrBuilder getSystemObjectsOrBuilder(
        int index) {
      return systemObjects_.get(index);
    }

    private void initFields() {
      name_ = "";
      systemObjects_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSystemObjectsCount(); i++) {
        if (!getSystemObjects(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < systemObjects_.size(); i++) {
        output.writeMessage(2, systemObjects_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < systemObjects_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, systemObjects_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fr.kissy.hellion.proto.common.ObjectDto.ObjectProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fr.kissy.hellion.proto.common.ObjectDto.ObjectProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ObjectProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fr.kissy.hellion.proto.common.ObjectDto.ObjectProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fr.kissy.hellion.proto.common.ObjectDto.internal_static_ObjectProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fr.kissy.hellion.proto.common.ObjectDto.internal_static_ObjectProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.class, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.Builder.class);
      }

      // Construct using fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSystemObjectsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (systemObjectsBuilder_ == null) {
          systemObjects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          systemObjectsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fr.kissy.hellion.proto.common.ObjectDto.internal_static_ObjectProto_descriptor;
      }

      public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto getDefaultInstanceForType() {
        return fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.getDefaultInstance();
      }

      public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto build() {
        fr.kissy.hellion.proto.common.ObjectDto.ObjectProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto buildPartial() {
        fr.kissy.hellion.proto.common.ObjectDto.ObjectProto result = new fr.kissy.hellion.proto.common.ObjectDto.ObjectProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (systemObjectsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            systemObjects_ = java.util.Collections.unmodifiableList(systemObjects_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.systemObjects_ = systemObjects_;
        } else {
          result.systemObjects_ = systemObjectsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fr.kissy.hellion.proto.common.ObjectDto.ObjectProto) {
          return mergeFrom((fr.kissy.hellion.proto.common.ObjectDto.ObjectProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fr.kissy.hellion.proto.common.ObjectDto.ObjectProto other) {
        if (other == fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (systemObjectsBuilder_ == null) {
          if (!other.systemObjects_.isEmpty()) {
            if (systemObjects_.isEmpty()) {
              systemObjects_ = other.systemObjects_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSystemObjectsIsMutable();
              systemObjects_.addAll(other.systemObjects_);
            }
            onChanged();
          }
        } else {
          if (!other.systemObjects_.isEmpty()) {
            if (systemObjectsBuilder_.isEmpty()) {
              systemObjectsBuilder_.dispose();
              systemObjectsBuilder_ = null;
              systemObjects_ = other.systemObjects_;
              bitField0_ = (bitField0_ & ~0x00000002);
              systemObjectsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSystemObjectsFieldBuilder() : null;
            } else {
              systemObjectsBuilder_.addAllMessages(other.systemObjects_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getSystemObjectsCount(); i++) {
          if (!getSystemObjects(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fr.kissy.hellion.proto.common.ObjectDto.ObjectProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fr.kissy.hellion.proto.common.ObjectDto.ObjectProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated .ObjectProto.SystemObjectProto systemObjects = 2;
      private java.util.List<fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto> systemObjects_ =
        java.util.Collections.emptyList();
      private void ensureSystemObjectsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          systemObjects_ = new java.util.ArrayList<fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto>(systemObjects_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProtoOrBuilder> systemObjectsBuilder_;

      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public java.util.List<fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto> getSystemObjectsList() {
        if (systemObjectsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(systemObjects_);
        } else {
          return systemObjectsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public int getSystemObjectsCount() {
        if (systemObjectsBuilder_ == null) {
          return systemObjects_.size();
        } else {
          return systemObjectsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto getSystemObjects(int index) {
        if (systemObjectsBuilder_ == null) {
          return systemObjects_.get(index);
        } else {
          return systemObjectsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public Builder setSystemObjects(
          int index, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto value) {
        if (systemObjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemObjectsIsMutable();
          systemObjects_.set(index, value);
          onChanged();
        } else {
          systemObjectsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public Builder setSystemObjects(
          int index, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder builderForValue) {
        if (systemObjectsBuilder_ == null) {
          ensureSystemObjectsIsMutable();
          systemObjects_.set(index, builderForValue.build());
          onChanged();
        } else {
          systemObjectsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public Builder addSystemObjects(fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto value) {
        if (systemObjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemObjectsIsMutable();
          systemObjects_.add(value);
          onChanged();
        } else {
          systemObjectsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public Builder addSystemObjects(
          int index, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto value) {
        if (systemObjectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSystemObjectsIsMutable();
          systemObjects_.add(index, value);
          onChanged();
        } else {
          systemObjectsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public Builder addSystemObjects(
          fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder builderForValue) {
        if (systemObjectsBuilder_ == null) {
          ensureSystemObjectsIsMutable();
          systemObjects_.add(builderForValue.build());
          onChanged();
        } else {
          systemObjectsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public Builder addSystemObjects(
          int index, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder builderForValue) {
        if (systemObjectsBuilder_ == null) {
          ensureSystemObjectsIsMutable();
          systemObjects_.add(index, builderForValue.build());
          onChanged();
        } else {
          systemObjectsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public Builder addAllSystemObjects(
          java.lang.Iterable<? extends fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto> values) {
        if (systemObjectsBuilder_ == null) {
          ensureSystemObjectsIsMutable();
          super.addAll(values, systemObjects_);
          onChanged();
        } else {
          systemObjectsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public Builder clearSystemObjects() {
        if (systemObjectsBuilder_ == null) {
          systemObjects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          systemObjectsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public Builder removeSystemObjects(int index) {
        if (systemObjectsBuilder_ == null) {
          ensureSystemObjectsIsMutable();
          systemObjects_.remove(index);
          onChanged();
        } else {
          systemObjectsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder getSystemObjectsBuilder(
          int index) {
        return getSystemObjectsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProtoOrBuilder getSystemObjectsOrBuilder(
          int index) {
        if (systemObjectsBuilder_ == null) {
          return systemObjects_.get(index);  } else {
          return systemObjectsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public java.util.List<? extends fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProtoOrBuilder> 
           getSystemObjectsOrBuilderList() {
        if (systemObjectsBuilder_ != null) {
          return systemObjectsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(systemObjects_);
        }
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder addSystemObjectsBuilder() {
        return getSystemObjectsFieldBuilder().addBuilder(
            fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.getDefaultInstance());
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder addSystemObjectsBuilder(
          int index) {
        return getSystemObjectsFieldBuilder().addBuilder(
            index, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.getDefaultInstance());
      }
      /**
       * <code>repeated .ObjectProto.SystemObjectProto systemObjects = 2;</code>
       */
      public java.util.List<fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder> 
           getSystemObjectsBuilderList() {
        return getSystemObjectsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProtoOrBuilder> 
          getSystemObjectsFieldBuilder() {
        if (systemObjectsBuilder_ == null) {
          systemObjectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProto.Builder, fr.kissy.hellion.proto.common.ObjectDto.ObjectProto.SystemObjectProtoOrBuilder>(
                  systemObjects_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          systemObjects_ = null;
        }
        return systemObjectsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ObjectProto)
    }

    static {
      defaultInstance = new ObjectProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ObjectProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ObjectProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ObjectProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ObjectProto_SystemObjectProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ObjectProto_SystemObjectProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031Proto/Common/Object.proto\032\031Proto/Commo" +
      "n/System.proto\032\033Proto/Common/Property.pr" +
      "oto\"\300\001\n\013ObjectProto\022\014\n\004name\030\001 \002(\t\0225\n\rsys" +
      "temObjects\030\002 \003(\0132\036.ObjectProto.SystemObj" +
      "ectProto\032l\n\021SystemObjectProto\022%\n\nsystemT" +
      "ype\030\n \002(\0162\021.SystemProto.Type\022\"\n\nproperti" +
      "es\030\013 \003(\0132\016.PropertyProto\022\014\n\004type\030\014 \001(\tB-" +
      "\n\035fr.kissy.hellion.proto.commonB\tObjectD" +
      "to\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ObjectProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ObjectProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ObjectProto_descriptor,
              new java.lang.String[] { "Name", "SystemObjects", });
          internal_static_ObjectProto_SystemObjectProto_descriptor =
            internal_static_ObjectProto_descriptor.getNestedTypes().get(0);
          internal_static_ObjectProto_SystemObjectProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ObjectProto_SystemObjectProto_descriptor,
              new java.lang.String[] { "SystemType", "Properties", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fr.kissy.hellion.proto.common.SystemDto.getDescriptor(),
          fr.kissy.hellion.proto.common.PropertyDto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
